#include<stdio.h>
#include<conio.h>

void main(){
clrscr();
printf("        ");
printf("I      |\n");
printf("R     |\n");
printf("N      |\n");
printf("W     |\n");
printf("I      |\n");
printf("        ");

printf("*\n");
printf("**\n");
printf("***\n");
printf("**\n");
printf("*\n");

printf("*\n");
printf("*\n");
printf("*\n");
printf("*      * *       *\n");
printf("*     *   *     *\n");
printf("*    *     *   *\n");
printf("*   *       * *\n");
printf("* *\n");
printf("*\n");

getch();
}